# Default values for demo-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: foo
namespace: default
baseDnsDomain: rw.com
#pullSecret
#sshPublicKey
